"""
Emit LaTeX snippet with oracle top-k and LLM-mapped codes for narrative flagship cells.
Run from repo root: python analysis/build_flagship_appendix.py
Output: paper/generated_paper/flagship_trace.tex
"""
from __future__ import annotations

import json
import pathlib
import sys
from collections import Counter

import pandas as pd

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(REPO_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "src"))

from survey_features.layout import resolve_llm_artifact

OUT_PATH = REPO_ROOT / "paper" / "generated_paper" / "flagship_trace.tex"

# (folder under outputs/, condition, display title)
FLAGSHIPS: list[tuple[str, str, str]] = [
    (
        "Q104_Kuwait",
        "country_provided",
        r"Arab Barometer \texttt{Q104} $\times$ Kuwait (\texttt{country\_provided}) — negative value-over-random cluster",
    ),
    (
        "SEXO_Colombia",
        "unprompted",
        r"Latinobarometer \texttt{SEXO} $\times$ Colombia (\texttt{unprompted}) — near-deterministic oracle, model trails random",
    ),
    (
        "SE7a_Mongolia",
        "country_provided",
        r"Asian Barometer \texttt{SE7a} $\times$ Mongolia (\texttt{country\_provided}) — large positive value-over-random",
    ),
]


def tex_escape(s: str) -> str:
    s = s.replace("\\", "\\textbackslash{}")
    s = s.replace("&", "\\&")
    s = s.replace("%", "\\%")
    s = s.replace("#", "\\#")
    s = s.replace("_", "\\_")
    return s


def oracle_top_table(folder: pathlib.Path, k: int = 5) -> tuple[str, str | None]:
    path = folder / "oracle.csv"
    df = pd.read_csv(path)
    pos = df[df["importance_mean"] > 1e-12].sort_values("importance_mean", ascending=False)

    tie_note: str | None = None
    if len(pos) == 0:
        show = df.sort_values("importance_mean", ascending=False).head(min(k, len(df)))
    elif len(pos) <= 3:
        show = pos
        if len(pos) == 1 and len(df) > 1:
            tie_note = (
                r"\textit{\footnotesize Only one feature has a strictly positive permutation mean in this "
                r"export; all other variables tie at zero.}"
            )
    else:
        show = pos.head(max(k, 5))

    lines = [
        r"\begin{tabular}{lrr}",
        r"\toprule",
        r"Feature & Imp.\ mean & Imp.\ std \\",
        r"\midrule",
    ]
    for _, r in show.iterrows():
        lines.append(
            f"{tex_escape(str(r['feature_variable']))} & {r['importance_mean']:.4f} & {r['importance_std']:.4f} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines), tie_note


def mapped_features_list(disambig_path: pathlib.Path, condition: str) -> str:
    raw = json.loads(disambig_path.read_text(encoding="utf-8"))
    rows = [x for x in raw if x.get("condition") == condition]
    rows.sort(key=lambda x: x.get("feature_rank", 0))
    items = []
    for x in rows:
        d = x.get("disambig") or {}
        code = d.get("selected_code") or "none"
        label = tex_escape(str(x.get("feature_label", "")))
        code_e = tex_escape(str(code))
        items.append(f"\\item \\texttt{{{code_e}}} (requested: {label})")
    selections = [(x.get("disambig") or {}).get("selected_code") or "none" for x in rows]
    cnt = Counter(selections)
    none_k = cnt.pop("none", 0)
    multiset_parts = [
        f"\\texttt{{{tex_escape(str(k))}}} $\\times$ {v}" for k, v in sorted(cnt.items())
    ]
    multiset_body = ", ".join(multiset_parts) if multiset_parts else "(no codes bound---all abstentions)"
    tail = "\\textit{\\footnotesize Selection multiset:} " + multiset_body
    if none_k:
        tail += f"; abstentions (\\texttt{{none}}): {none_k}"
    tail += "."
    if none_k >= 2:
        tail += (
            r" \textit{\footnotesize Several abstentions mean the model declined every shortlist candidate for those prompts; downstream \(k_{\mathrm{mapped}}\) still follows deduplicated binds in \texttt{eval.json}.}"
        )
    return "\\begin{itemize}\n" + "\n".join(items) + "\n\\end{itemize}\n\n" + tail


def main() -> None:
    chunks = [
        "% Auto-generated by analysis/build_flagship_appendix.py",
        r"\subsection{Flagship cells: oracle top features vs.\ mapped LLM variables}\label{sec:flagship-trace}",
        r"\small",
        r"\noindent Each block lists permutation-importance leaders from \texttt{oracle.csv} (may include sampling weights or design fields; interpret as diagnostic) juxtaposed against the sequential LLM disambiguation log. Repeated \texttt{none} selections are adjudicated abstentions from the shortlisted candidates; realised \(k_{\mathrm{mapped}}\) for evaluation always comes from \texttt{eval.json}, not raw request counts.",
    ]
    for subdir, condition, title in FLAGSHIPS:
        folder = REPO_ROOT / "outputs" / subdir
        if not folder.is_dir():
            chunks.append(f"% Missing folder: {subdir}")
            continue
        target, country = subdir.rsplit("_", 1)
        k = 5
        try:
            ev_path = resolve_llm_artifact(REPO_ROOT / "outputs", target, country, "eval.json")
            if ev_path and ev_path.is_file():
                ev = json.loads(ev_path.read_text(encoding="utf-8"))
                k = int(ev["results"][condition].get("k_mapped", k))
        except (KeyError, json.JSONDecodeError, TypeError):
            pass
        chunks.append(r"\subsubsection*{" + title + "}")
        chunks.append(r"\paragraph{Oracle features (positive permutation importance first; up to \(k=k_{\mathrm{mapped}}\) contextual)}")
        tab, remark = oracle_top_table(folder, k=max(5, k))
        chunks.append(tab)
        if remark:
            chunks.append(remark)
        chunks.append(r"\paragraph{LLM-mapped variables (this condition)}")
        dis_path = resolve_llm_artifact(REPO_ROOT / "outputs", target, country, "disambig.json")
        if dis_path and dis_path.is_file():
            chunks.append(mapped_features_list(dis_path, condition))
        else:
            chunks.append("% Missing disambig.json (set GRID_SUMMARY_TAG or add llm__* cache)")
        chunks.append(r"\vspace{0.6em}")
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n\n".join(chunks) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
